[package]
name = "xxfunc-db"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
r2d2_sqlite.workspace = true
rusqlite.workspace = true
eyre.workspace = true
r2d2.workspace = true
tempfile.workspace = true
